version: 1.0.{build}
configuration: Debug
before_build:
- cmd: git submodule init
- cmd: dir
- cmd: dir 3rdparty
- cmd: dir 3rdparty\mpc
- cmd: perl -v
- cmd: perl 3rdparty\mpc\mwc.pl -type vc14 -include tools/mpc
build:
  verbosity: minimal