version: 1.0.{build}
configuration: Debug

before_build:
- cmd: git submodule init
- cmd: git submodule update
- cmd: perl 3rdparty\mpc\mwc.pl -type vc14 -include tools/mpc

build:
  verbosity: minimal

test_script:
- cmd: dir modules\example
- cmd: dir modules\example\Debug
- cmd: modules\example\foo.exe